### ISSUE TITLE
dde_zircon

### ISSUE THREAD

**Issue by jklmnn** [jklmnn/genode#3]
The idea is to create a device driver environment to use [Zircon](https://github.com/fuchsia-mirror/zircon) drivers on Genode.

The [system calls](https://github.com/fuchsia-mirror/zircon/blob/master/docs/syscalls.md) seem to be related with Linux but the overall interface is far less complex. To pass capabilities [handles](https://github.com/fuchsia-mirror/zircon/blob/master/docs/handles.md) are used but they are defined as unsigned 32 bit integers and therefore can't be used to pass Genode capabilities directly. Also their usage does not always fit with what I would expect and what would help to implement it on Genode. For example interrupts get a new handle which is then passed to each interrupt action. This fits nicely with Genodes IRQ session except that the session capability needs to be mapped to a 32 bit integer value. IO ports are different. The process once requests a certain port range but this call doesn't return a handle. Furthermore a inb call (named `inp` for whatever reason) is inlined as assembly into the driver code. I had to replace the header since this won't work with Genode at all otherwise.
Also they use their own libc that is included in the repository. Using Genodes libc was not possible since some definition collision will occur then. The part currently used are only declarations and a printf implementation so this isn't a real deal breaker.
Disclaimer: It could be that I misunderstood some parts of the API and that everything is really simple but this is the best solution I could come up with.

The driver binding mechanism is a special case on its own. Each driver object (as in linker object) provides a symbol `__zircon_driver_rec__` in its data section which is a `zx_driver_rec_t` that contains an `ops` field. This is a struct that contains function pointers to different methods (in the ps2 driver case to `bind` only) that can be called by the system. I assume that this way was chosen since components in Zircon are loaded as dynamic libraries.

To get a starting point I chose the `pc-ps2` x86 PS2 driver since it isn't overly complex and should be easy to test as it is an architecture wide available peripheral.
The current state (https://github.com/jklmnn/genode/commit/12214d563ec511f095962ca2939f98dbc9fe2f83) is that I can start the driver, some resources are alreay requested but it segfaults at some point. This is somehow expected as I pass nullpointer as arguments and have yet to figure out what the `bind` method expects exactly and how I can provide that.

When the PS2 driver works I plan to refactor the whole thing and create a `zircon.lib.so` shared library that provides the syscalls and required libc directives.

**Comment by jklmnn** [comment]
With c834a725a2572614a07f3f2e364ba8402fe3549e we have a working PS2 driver (at least if you add some output to the driver code). Interrupt and IO port mappings for the platform driver need to be provided by driver main function.

**Comment by jklmnn** [comment]
The data is provided via the `proto_ops` of the device args that are passed to `add_device_from_driver`. In this case this is a `hidbus_protocol_ops_t` which contains a `start` function pointer that takes the `hidbus_ifc_t` which contains a function pointer to the callback when data is available.

**Comment by senier** [comment]
So the next step would be to make the driver provide a Genode Input session? How is the input interface realized in Zircon?

**Comment by jklmnn** [comment]
The callback (as described in the comment before) gets a void pointer and a length. So I can check on the length to which struct type (keyboard or mouse) i have to cast the pointer (this is as dirty as it sounds but there seems to be no type field). The mouse struct contains relative movements which are the same as used in Genode (this is the only working part of the input session, if you run the demo with my driver you can at least move the mouse ;)). I did not find out yet how the mouse buttons are encoded. Also the keycodes are completely different. Furthermore there is no press and release event but a queue with up to six buttons that can be pressed simultaneously. A release would be a key that is in the queue and disappears then.

Yet these are minor problems since I have all the information I need in Genode. The next step will be a zircon.lib.so built upon a Zircon namespace that provides generic interfaces such as threads or interrupts.

**Comment by jklmnn** [comment]
The handler function for theh returned data gets an array of keys that are currently pressed. This is used to determine press and release events. Also the key codes are completely different so I had to create a map between both keymaps.

**Comment by jklmnn** [comment]
Fixed with https://github.com/genodelabs/genode/pull/2926.

**Comment by jklmnn** [comment]
Fixed with https://github.com/genodelabs/genode/pull/3044.
